### ISSUE TITLE
is it possible to upload the full tree ?

### ISSUE THREAD

**Issue by teto** [1989chenguo/FUSO#1]
It makes it easier to see what the changes are as I could use github UI to see the changes instead of cloning this/mptcp/moving files over and generating the patch myself.
I could do it but the current presentation is suboptimal imo.

**Comment by 1989chenguo** [comment]
Hi teto,

Really sorry for the late response because I just find the email in my spam mailbox...

You can just clone the original MPTCP repo, and download my source code and just copy & overwrite them into the original MPTCP folders. I have kept the same folder structure so it would not be difficult to do so.

Thanks
Guo

**Comment by 1989chenguo** [comment]
Hi teto,

Really sorry for the late response because I just find the email in my spam mailbox...

You can just clone the original MPTCP repo, and download my source code and just copy & overwrite them into the original MPTCP folders. I have kept the same folder structure so it would not be difficult to do so.

Thanks
Guo
